export class Student {
    id?: number = 0;
    code?: string = '';
    guid?: string = '';
    first_name_ar?: string = '';
    middle_name_ar?: string = '';
    grand_name_ar?: string = '';
    surname_ar?: string = '';
    first_name_en?: string = '';
    middle_name_en?: string = '';
    grand_name_en?: string = '';
    surname_en?: string = '';
    first_name_fr?: string = '';
    middle_name_fr?: string = '';
    grand_name_fr?: string = '';
    surname_fr?: string = '';
    program_code?: string = '';
    program_regulation_id?: string = '';
    start?: string = '';
    end?: string = '';
    academy_id?: number = 0;
    academy_code?: string = '';
    student_case?: string = '';
    sitting_number?: string = '';
    person_id?: number = 0;
    current_job?: string = '';
    current_job_location?: string = '';
    is_active?: boolean | false;
    religion?: string = '';
    gender?: string = '';
    attachment_receive?: number = 0;
    gpa?: number = 0;
    created?: string = '';
    updated?: string = '';
    first_name?: { ar: string, en: string, fr: string } = { 'ar': '', 'en': '', 'fr': '' };
    middle_name?: { ar: string, en: string, fr: string } = { 'ar': '', 'en': '', 'fr': '' };
    grand_name?: { ar: string, en: string, fr: string } = { 'ar': '', 'en': '', 'fr': '' };
    surname?: { ar: string, en: string, fr: string } = { 'ar': '', 'en': '', 'fr': '' };
    academy_name?: { ar: string, en: string } = { 'ar': '', 'en': '' };
    is_approve?: string = '';
    suggestion_date_action: string;
    approvel_date_action: string;
    subject: string;
    comments: string;
    step_status: string;
    bcase_trn_id: number;
    bcase_trn_relative_id: number;
    draft_id: number;
    approved_flag: string;
    tansik_status: string;
    insert_user_id: number;
    insert_timestamp: Date;
    citizen_serial: string = '';
    student_grade:number= 0;
    total_grade:number= 0;
    is_confirm: boolean = false;
    category_flag:number= 0;
    is_fit?:string='';
    approve_type?:string='';
    refuse_type?:string='';
    registration_type_code?:string='';
    military_id?:string='';
    enlistment_status_id?:string='';
}